"""Type stubs for the cydsp._core C++ extension module."""

from __future__ import annotations

import enum
from typing import Self

import numpy as np
from numpy.typing import NDArray

def add(a: int, b: int) -> int: ...
def greet(name: str) -> str: ...

class filters:
    class BiquadDesign(enum.IntEnum):
        bilinear: int
        cookbook: int
        one_sided: int
        vicanek: int

    class Biquad:
        def __init__(self) -> None: ...
        def lowpass(
            self,
            freq: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def lowpass_q(
            self,
            freq: float,
            q: float,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def highpass(
            self,
            freq: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def highpass_q(
            self,
            freq: float,
            q: float,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def bandpass(
            self,
            freq: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def bandpass_q(
            self,
            freq: float,
            q: float,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def notch(
            self,
            freq: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def notch_q(
            self,
            freq: float,
            q: float,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def peak(
            self,
            freq: float,
            gain: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def peak_db(
            self,
            freq: float,
            db: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def high_shelf(
            self,
            freq: float,
            gain: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def high_shelf_db(
            self,
            freq: float,
            db: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def low_shelf(
            self,
            freq: float,
            gain: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def low_shelf_db(
            self,
            freq: float,
            db: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def allpass(
            self,
            freq: float,
            octaves: float = ...,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def allpass_q(
            self,
            freq: float,
            q: float,
            design: filters.BiquadDesign = ...,
        ) -> Self: ...
        def add_gain(self, factor: float) -> Self: ...
        def add_gain_db(self, db: float) -> Self: ...
        def reset(self) -> None: ...
        def response(self, freq: float) -> complex: ...
        def response_db(self, freq: float) -> float: ...
        def process(self, input: np.ndarray) -> NDArray[np.float32]: ...
        def process_inplace(self, buffer: np.ndarray) -> None: ...

class fft:
    class FFT:
        def __init__(self, size: int, fast_direction: int = ...) -> None: ...
        def size(self) -> int: ...
        def set_size(self, size: int) -> None: ...
        @staticmethod
        def fast_size_above(size: int) -> int: ...
        @staticmethod
        def fast_size_below(size: int) -> int: ...
        def fft(self, input: np.ndarray) -> NDArray[np.complex64]: ...
        def ifft(self, input: np.ndarray) -> NDArray[np.complex64]: ...

    class RealFFT:
        def __init__(self, size: int, fast_direction: int = ...) -> None: ...
        def size(self) -> int: ...
        def set_size(self, size: int) -> None: ...
        @staticmethod
        def fast_size_above(size: int) -> int: ...
        @staticmethod
        def fast_size_below(size: int) -> int: ...
        def fft(self, input: np.ndarray) -> NDArray[np.complex64]: ...
        def ifft(self, input: np.ndarray) -> NDArray[np.float32]: ...

class delay:
    class Delay:
        latency: int
        def __init__(self, capacity: int = ...) -> None: ...
        def reset(self, value: float = ...) -> None: ...
        def resize(self, capacity: int, value: float = ...) -> None: ...
        def process(
            self, input: np.ndarray, delay_samples: float
        ) -> NDArray[np.float32]: ...
        def process_varying(
            self, input: np.ndarray, delays: np.ndarray
        ) -> NDArray[np.float32]: ...

    class DelayCubic:
        latency: int
        def __init__(self, capacity: int = ...) -> None: ...
        def reset(self, value: float = ...) -> None: ...
        def resize(self, capacity: int, value: float = ...) -> None: ...
        def process(
            self, input: np.ndarray, delay_samples: float
        ) -> NDArray[np.float32]: ...
        def process_varying(
            self, input: np.ndarray, delays: np.ndarray
        ) -> NDArray[np.float32]: ...

class envelopes:
    class CubicLfo:
        def __init__(self, seed: int = ...) -> None: ...
        def reset(self) -> None: ...
        def set(
            self,
            low: float,
            high: float,
            rate: float,
            rate_variation: float = ...,
            depth_variation: float = ...,
        ) -> None: ...
        def next(self) -> float: ...
        def process(self, n: int) -> NDArray[np.float32]: ...

    class BoxFilter:
        def __init__(self, max_length: int) -> None: ...
        def resize(self, max_length: int) -> None: ...
        def set(self, length: int) -> None: ...
        def reset(self, fill: float = ...) -> None: ...
        def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

    class BoxStackFilter:
        def __init__(self, max_size: int, layers: int = ...) -> None: ...
        def set(self, size: int) -> None: ...
        def reset(self, fill: float = ...) -> None: ...
        def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

    class PeakHold:
        def __init__(self, max_length: int) -> None: ...
        def resize(self, max_length: int) -> None: ...
        def set(self, new_size: int, preserve_current_peak: bool = ...) -> None: ...
        def reset(self, fill: float = ...) -> None: ...
        def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

    class PeakDecayLinear:
        def __init__(self, max_length: int) -> None: ...
        def resize(self, max_length: int) -> None: ...
        def set(self, length: int) -> None: ...
        def reset(self, start: float = ...) -> None: ...
        def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

class spectral:
    class STFT:
        def __init__(
            self,
            channels: int,
            window_size: int,
            interval: int,
            history_length: int = ...,
            zero_padding: int = ...,
        ) -> None: ...
        def window_size(self) -> int: ...
        def fft_size(self) -> int: ...
        def interval(self) -> int: ...
        def bands(self) -> int: ...
        def latency(self) -> int: ...
        def reset(self) -> None: ...
        def analyse(self, input: np.ndarray) -> None: ...
        def analyse_channel(self, channel: int, input: np.ndarray) -> None: ...
        def get_spectrum(self) -> NDArray[np.complex64]: ...
        def get_spectrum_channel(self, channel: int) -> NDArray[np.complex64]: ...
        def set_spectrum_channel(self, channel: int, data: np.ndarray) -> None: ...

class rates:
    class Oversampler2x:
        def __init__(
            self,
            channels: int,
            max_block: int,
            half_latency: int = ...,
            pass_freq: float = ...,
        ) -> None: ...
        def reset(self) -> None: ...
        def latency(self) -> int: ...
        def up(self, input: np.ndarray) -> NDArray[np.float32]: ...
        def down(self, input: np.ndarray, low_samples: int) -> NDArray[np.float32]: ...
        def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

class mix:
    class Hadamard:
        def __init__(self, size: int) -> None: ...
        def in_place(self, data: np.ndarray) -> NDArray[np.float32]: ...
        def scaling_factor(self) -> float: ...

    class Householder:
        def __init__(self, size: int) -> None: ...
        def in_place(self, data: np.ndarray) -> NDArray[np.float32]: ...

    @staticmethod
    def cheap_energy_crossfade(x: float) -> tuple[float, float]: ...

class daisysp:
    class oscillators:
        WAVE_SIN: int
        WAVE_TRI: int
        WAVE_SAW: int
        WAVE_RAMP: int
        WAVE_SQUARE: int
        WAVE_POLYBLEP_TRI: int
        WAVE_POLYBLEP_SAW: int
        WAVE_POLYBLEP_SQUARE: int
        BLOSC_WAVE_TRIANGLE: int
        BLOSC_WAVE_SAW: int
        BLOSC_WAVE_SQUARE: int
        BLOSC_WAVE_OFF: int

        class Oscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_amp(self, amp: float) -> None: ...
            def set_waveform(self, waveform: int) -> None: ...
            def set_pw(self, pw: float) -> None: ...
            def phase_add(self, phase: float) -> None: ...
            def reset(self, phase: float = ...) -> None: ...
            def is_eor(self) -> bool: ...
            def is_eoc(self) -> bool: ...
            def is_rising(self) -> bool: ...
            def is_falling(self) -> bool: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Fm2:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_frequency(self, freq: float) -> None: ...
            def set_ratio(self, ratio: float) -> None: ...
            def set_index(self, index: float) -> None: ...
            def get_index(self) -> float: ...
            def reset(self) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class FormantOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_formant_freq(self, freq: float) -> None: ...
            def set_carrier_freq(self, freq: float) -> None: ...
            def set_phase_shift(self, ps: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class HarmonicOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_first_harm_idx(self, idx: int) -> None: ...
            def set_amplitudes(self, amplitudes: np.ndarray) -> None: ...
            def set_single_amp(self, amp: float, idx: int) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class OscillatorBank:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_amplitudes(self, amplitudes: np.ndarray) -> None: ...
            def set_single_amp(self, amp: float, idx: int) -> None: ...
            def set_gain(self, gain: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class VariableSawOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_pw(self, pw: float) -> None: ...
            def set_waveshape(self, waveshape: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class VariableShapeOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_pw(self, pw: float) -> None: ...
            def set_waveshape(self, waveshape: float) -> None: ...
            def set_sync(self, enable_sync: bool) -> None: ...
            def set_sync_freq(self, freq: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class VosimOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_form1_freq(self, freq: float) -> None: ...
            def set_form2_freq(self, freq: float) -> None: ...
            def set_shape(self, shape: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class ZOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_formant_freq(self, freq: float) -> None: ...
            def set_shape(self, shape: float) -> None: ...
            def set_mode(self, mode: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class BlOsc:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_amp(self, amp: float) -> None: ...
            def set_pw(self, pw: float) -> None: ...
            def set_waveform(self, waveform: int) -> None: ...
            def reset(self) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

    class filters:
        class Svf:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_res(self, res: float) -> None: ...
            def set_drive(self, drive: float) -> None: ...
            def process_sample(
                self, in_: float
            ) -> tuple[float, float, float, float, float]: ...
            def low(self) -> float: ...
            def high(self) -> float: ...
            def band(self) -> float: ...
            def notch(self) -> float: ...
            def peak(self) -> float: ...
            def process_low(self, input: np.ndarray) -> NDArray[np.float32]: ...
            def process_high(self, input: np.ndarray) -> NDArray[np.float32]: ...
            def process_band(self, input: np.ndarray) -> NDArray[np.float32]: ...
            def process_notch(self, input: np.ndarray) -> NDArray[np.float32]: ...
            def process_peak(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class OnePoleFM(enum.IntEnum):
            LOW_PASS: int
            HIGH_PASS: int

        class OnePole:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def reset(self) -> None: ...
            def set_frequency(self, freq: float) -> None: ...
            def set_filter_mode(self, mode: daisysp.filters.OnePoleFM) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class LadderFilterMode(enum.IntEnum):
            LP24: int
            LP12: int
            BP24: int
            BP12: int
            HP24: int
            HP12: int

        class LadderFilter:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_res(self, res: float) -> None: ...
            def set_passband_gain(self, pbg: float) -> None: ...
            def set_input_drive(self, drv: float) -> None: ...
            def set_filter_mode(
                self, mode: daisysp.filters.LadderFilterMode
            ) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Soap:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_center_freq(self, freq: float) -> None: ...
            def set_filter_bandwidth(self, bandwidth: float) -> None: ...
            def process_sample(self, in_: float) -> tuple[float, float]: ...
            def bandpass(self) -> float: ...
            def bandreject(self) -> float: ...
            def process_bandpass(self, input: np.ndarray) -> NDArray[np.float32]: ...
            def process_bandreject(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Allpass:
            def __init__(self, sample_rate: float, max_size: int = ...) -> None: ...
            def set_freq(self, looptime: float) -> None: ...
            def set_rev_time(self, revtime: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class ATone:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def get_freq(self) -> float: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class DaisyBiquad:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_res(self, res: float) -> None: ...
            def set_cutoff(self, cutoff: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Comb:
            def __init__(self, sample_rate: float, max_size: int = ...) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_period(self, looptime: float) -> None: ...
            def set_rev_time(self, revtime: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Mode:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_q(self, q: float) -> None: ...
            def clear(self) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class MoogLadder:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_res(self, res: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class NlFilt:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_coefficients(
                self, a: float, b: float, d: float, C: float, L: float
            ) -> None: ...
            def set_a(self, a: float) -> None: ...
            def set_b(self, b: float) -> None: ...
            def set_d(self, d: float) -> None: ...
            def set_c(self, C: float) -> None: ...
            def set_l(self, L: float) -> None: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Tone:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def get_freq(self) -> float: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

    class effects:
        class Autowah:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_wah(self, wah: float) -> None: ...
            def set_dry_wet(self, drywet: float) -> None: ...
            def set_level(self, level: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Chorus:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_lfo_depth(self, depth: float) -> None: ...
            def set_lfo_freq(self, freq: float) -> None: ...
            def set_delay(self, delay: float) -> None: ...
            def set_delay_ms(self, ms: float) -> None: ...
            def set_feedback(self, feedback: float) -> None: ...
            def get_left(self) -> float: ...
            def get_right(self) -> float: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...
            def process_stereo(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Decimator:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_downsample_factor(self, factor: float) -> None: ...
            def set_bitcrush_factor(self, factor: float) -> None: ...
            def set_bits_to_crush(self, bits: int) -> None: ...
            def set_smooth_crushing(self, enable: bool) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Flanger:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_feedback(self, feedback: float) -> None: ...
            def set_lfo_depth(self, depth: float) -> None: ...
            def set_lfo_freq(self, freq: float) -> None: ...
            def set_delay(self, delay: float) -> None: ...
            def set_delay_ms(self, ms: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Overdrive:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_drive(self, drive: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Phaser:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_poles(self, poles: int) -> None: ...
            def set_lfo_depth(self, depth: float) -> None: ...
            def set_lfo_freq(self, freq: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_feedback(self, feedback: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class PitchShifter:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_transposition(self, semitones: float) -> None: ...
            def set_del_size(self, size: int) -> None: ...
            def set_fun(self, fun: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class SampleRateReducer:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Tremolo:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_waveform(self, waveform: int) -> None: ...
            def set_depth(self, depth: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Wavefolder:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_gain(self, gain: float) -> None: ...
            def set_offset(self, offset: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Bitcrush:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_bit_depth(self, depth: int) -> None: ...
            def set_crush_rate(self, rate: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Fold:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_increment(self, incr: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class ReverbSc:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_feedback(self, feedback: float) -> None: ...
            def set_lp_freq(self, freq: float) -> None: ...
            def process_sample(self, in1: float, in2: float) -> tuple[float, float]: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

    class dynamics:
        CROSSFADE_LIN: int
        CROSSFADE_CPOW: int
        CROSSFADE_LOG: int
        CROSSFADE_EXP: int

        class CrossFade:
            def __init__(self) -> None: ...
            def init(self, curve: int = ...) -> None: ...
            def set_pos(self, pos: float) -> None: ...
            def set_curve(self, curve: int) -> None: ...
            def process_sample(self, in1: float, in2: float) -> float: ...
            def process(
                self, input1: np.ndarray, input2: np.ndarray
            ) -> NDArray[np.float32]: ...

        class Limiter:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def process(
                self, input: np.ndarray, pre_gain: float = ...
            ) -> NDArray[np.float32]: ...

        class Balance:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_cutoff(self, cutoff: float) -> None: ...
            def process_sample(self, sig: float, comp: float) -> float: ...
            def process(
                self, sig: np.ndarray, comp: np.ndarray
            ) -> NDArray[np.float32]: ...

        class Compressor:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_ratio(self, ratio: float) -> None: ...
            def set_threshold(self, threshold: float) -> None: ...
            def set_attack(self, attack: float) -> None: ...
            def set_release(self, release: float) -> None: ...
            def set_makeup(self, gain: float) -> None: ...
            def auto_makeup(self, enable: bool) -> None: ...
            def get_ratio(self) -> float: ...
            def get_threshold(self) -> float: ...
            def get_attack(self) -> float: ...
            def get_release(self) -> float: ...
            def get_makeup(self) -> float: ...
            def get_gain(self) -> float: ...
            def process_sample(self, in_: float) -> float: ...
            def apply(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

    class control:
        ADENV_SEG_IDLE: int
        ADENV_SEG_ATTACK: int
        ADENV_SEG_DECAY: int
        ADSR_SEG_IDLE: int
        ADSR_SEG_ATTACK: int
        ADSR_SEG_DECAY: int
        ADSR_SEG_RELEASE: int

        class AdEnv:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trigger(self) -> None: ...
            def set_time(self, seg: int, time: float) -> None: ...
            def set_curve(self, scalar: float) -> None: ...
            def set_min(self, min: float) -> None: ...
            def set_max(self, max: float) -> None: ...
            def get_value(self) -> float: ...
            def get_current_segment(self) -> int: ...
            def is_running(self) -> bool: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Adsr:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float, block_size: int = ...) -> None: ...
            def retrigger(self, hard: bool) -> None: ...
            def set_attack_time(self, time: float) -> None: ...
            def set_decay_time(self, time: float) -> None: ...
            def set_release_time(self, time: float) -> None: ...
            def set_sustain_level(self, level: float) -> None: ...
            def set_time(self, seg: int, time: float) -> None: ...
            def get_current_segment(self) -> int: ...
            def is_running(self) -> bool: ...
            def process_sample(self, gate: bool) -> float: ...
            def process(self, gate: np.ndarray) -> NDArray[np.float32]: ...

        class Phasor:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float, freq: float = ...) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def get_freq(self) -> float: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Line:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def start(self, start: float, end: float, dur: float) -> None: ...
            def process(self, n: int) -> tuple[NDArray[np.float32], bool]: ...

    class noise:
        class WhiteNoise:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_amp(self, amp: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Dust:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def set_density(self, density: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class ClockedNoise:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def sync(self) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class FractalRandomGenerator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_color(self, color: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class GrainletOscillator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_formant_freq(self, freq: float) -> None: ...
            def set_shape(self, shape: float) -> None: ...
            def set_bleed(self, bleed: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Particle:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_resonance(self, res: float) -> None: ...
            def set_random_freq(self, freq: float) -> None: ...
            def set_density(self, density: float) -> None: ...
            def set_gain(self, gain: float) -> None: ...
            def set_spread(self, spread: float) -> None: ...
            def set_sync(self, sync: bool) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class SmoothRandomGenerator:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

    class drums:
        class AnalogBassDrum:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_tone(self, tone: float) -> None: ...
            def set_decay(self, decay: float) -> None: ...
            def set_attack_fm_amount(self, amount: float) -> None: ...
            def set_self_fm_amount(self, amount: float) -> None: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class AnalogSnareDrum:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_tone(self, tone: float) -> None: ...
            def set_decay(self, decay: float) -> None: ...
            def set_snappy(self, snappy: float) -> None: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class HiHat:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_tone(self, tone: float) -> None: ...
            def set_decay(self, decay: float) -> None: ...
            def set_noisiness(self, noisiness: float) -> None: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class SyntheticBassDrum:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_tone(self, tone: float) -> None: ...
            def set_decay(self, decay: float) -> None: ...
            def set_dirtiness(self, dirtiness: float) -> None: ...
            def set_fm_envelope_amount(self, amount: float) -> None: ...
            def set_fm_envelope_decay(self, decay: float) -> None: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class SyntheticSnareDrum:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_fm_amount(self, amount: float) -> None: ...
            def set_decay(self, decay: float) -> None: ...
            def set_snappy(self, snappy: float) -> None: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

    class physical_modeling:
        PLUCK_MODE_RECURSIVE: int
        PLUCK_MODE_WEIGHTED_AVERAGE: int

        class Drip:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float, dettack: float) -> None: ...
            def process_sample(self, trig: bool) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class String:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def reset(self) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_non_linearity(self, amount: float) -> None: ...
            def set_brightness(self, brightness: float) -> None: ...
            def set_damping(self, damping: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class ModalVoice:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_structure(self, structure: float) -> None: ...
            def set_brightness(self, brightness: float) -> None: ...
            def set_damping(self, damping: float) -> None: ...
            def get_aux(self) -> float: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Resonator:
            def __init__(self) -> None: ...
            def init(
                self, position: float, resolution: int, sample_rate: float
            ) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_structure(self, structure: float) -> None: ...
            def set_brightness(self, brightness: float) -> None: ...
            def set_damping(self, damping: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class StringVoice:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def trig(self) -> None: ...
            def reset(self) -> None: ...
            def set_sustain(self, sustain: bool) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_accent(self, accent: float) -> None: ...
            def set_structure(self, structure: float) -> None: ...
            def set_brightness(self, brightness: float) -> None: ...
            def set_damping(self, damping: float) -> None: ...
            def get_aux(self) -> float: ...
            def process_sample(self, trigger: bool = ...) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Pluck:
            def __init__(
                self, sample_rate: float, npt: int = ..., mode: int = ...
            ) -> None: ...
            def set_amp(self, amp: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def set_decay(self, decay: float) -> None: ...
            def set_damp(self, damp: float) -> None: ...
            def set_mode(self, mode: int) -> None: ...
            def process_sample(self, trig: float) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

    class utility:
        class DcBlock:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class DelayLine:
            def __init__(self) -> None: ...
            def init(self) -> None: ...
            def reset(self) -> None: ...
            def set_delay(self, delay: float) -> None: ...
            def write(self, sample: float) -> None: ...
            def read(self) -> float: ...
            def read_at(self, delay: float) -> float: ...
            def read_hermite(self, delay: float) -> float: ...
            def process(
                self, input: np.ndarray, delay_samples: float
            ) -> NDArray[np.float32]: ...

        class LooperMode(enum.IntEnum):
            NORMAL: int
            ONETIME_DUB: int
            REPLACE: int
            FRIPPERTRONICS: int

        class Looper:
            def __init__(self, size: int = ...) -> None: ...
            def trig_record(self) -> None: ...
            def set_mode(self, mode: daisysp.utility.LooperMode) -> None: ...
            def get_mode(self) -> daisysp.utility.LooperMode: ...
            def set_reverse(self, state: bool) -> None: ...
            def toggle_reverse(self) -> None: ...
            def get_reverse(self) -> bool: ...
            def set_half_speed(self, state: bool) -> None: ...
            def toggle_half_speed(self) -> None: ...
            def get_half_speed(self) -> bool: ...
            def clear(self) -> None: ...
            def recording(self) -> bool: ...
            def is_near_beginning(self) -> bool: ...
            def process_sample(self, input: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...

        class Maytrig:
            def __init__(self) -> None: ...
            def process(self, prob: float) -> float: ...

        class Metro:
            def __init__(self) -> None: ...
            def init(self, freq: float, sample_rate: float) -> None: ...
            def set_freq(self, freq: float) -> None: ...
            def get_freq(self) -> float: ...
            def reset(self) -> None: ...
            def process_sample(self) -> bool: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class SampleHoldMode(enum.IntEnum):
            SAMPLE_HOLD: int
            TRACK_HOLD: int

        class SampleHold:
            def __init__(self) -> None: ...
            def process(
                self,
                trigger: bool,
                input: float,
                mode: daisysp.utility.SampleHoldMode = ...,
            ) -> float: ...

        class Jitter:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float) -> None: ...
            def set_cps_min(self, cps_min: float) -> None: ...
            def set_cps_max(self, cps_max: float) -> None: ...
            def set_amp(self, amp: float) -> None: ...
            def process_sample(self) -> float: ...
            def process(self, n: int) -> NDArray[np.float32]: ...

        class Port:
            def __init__(self) -> None: ...
            def init(self, sample_rate: float, htime: float) -> None: ...
            def set_htime(self, htime: float) -> None: ...
            def get_htime(self) -> float: ...
            def process_sample(self, in_: float) -> float: ...
            def process(self, input: np.ndarray) -> NDArray[np.float32]: ...
